createBook:
    path: /api/{version}/items
    controller: BookCatalogAPI\Controller\Items\CreateItemController
    methods: [POST]
    requirements:
        version: '%api_versions%'

GetBook:
    path: /api/{version}/items/{item}
    controller: BookCatalogAPI\Controller\Items\GetItemController
    methods: [GET]
    requirements:
        version: '%api_versions%'
